Portfolio-deployment.
Patfarmurs/Building-a-Portfolio pull request #4
Opened 2022-11-14 19:06 UTC by Patfarmurs

In this milestone : 
I deployed my Portfolio web page.
I added the Linters configuration.
I added a link to my online portfolio to 
the readme file.

2022-11-14 20:37 UTC, andgarzonmal requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 Hi @Patfarmurs    ✋🏼 

#### Your project is excellent. You are almost done. However, there are some issues you should fix. Please fix them and your project will be approved.

___ 

### 💯  Highlights 💯
- Your gitHub flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️

### ♻️ Request changes ♻️

- [x] _Check the comments below._

- [ ]  Kyndly add the link to your page on the readme file 

![image](https://user-images.githubusercontent.com/95243996/201760067-58201f02-2c0f-4e45-af32-006bcab80827.png)

- [ ]  Kyndly make sure the deployment shows all the images, as you can see your page is not showing the cards images.

![image](https://user-images.githubusercontent.com/95243996/201760126-19737901-3076-448a-8d74-033a1271bf6a.png)



___


### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-15 15:31 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @Patfarmurs, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 
-  App deployed properly. :heavy_check_mark: 
-  Readme file updated with live version link. :heavy_check_mark: 

![](https://camo.githubusercontent.com/f4e04d5e9518e3cbf972fb0f7611848a87ed4e1aa7770811bc22c5b957824887/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c3253716972355a78666f5332374576532f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 16:00 UTC, merged

2022-11-25 07:25 UTC, Thinus01 reviewed
Well done so for with your project.

2022-11-25 07:25 UTC, Thinus01 commented on index.html
> +                    <img src="./img/man-with-backpack-exploring-nature.jpg" alt="man exploring the nature">
Well done in adding alt tags to your image tags. This will made it easier for people with low bandwidth to browse your page.