Mobile menu 1
Patfarmurs/Building-a-Portfolio pull request #6
Opened 2022-11-24 06:25 UTC by Patfarmurs

In this milestone I : 
Add linters configuration
Use JavaScript to manipulate DOM elements
Use JavaScript events

2022-11-24 07:02 UTC, HAMMAS-SALEEM reviewed
# Invalid Review Request 🔴

## Hey @Patfarmurs, @ilyassatlassi :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Github flow
✔️ Following some requirements

Good job on implementing some of the requirements but i cannot proceed review on your pull request. There are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 07:02 UTC, HAMMAS-SALEEM commented on .eslintrc.json
> +{
![Invalid-Linters](https://user-images.githubusercontent.com/93039359/203715639-986ff9e9-54a5-4d42-8e58-79840be660da.PNG)

- [ ] Kindly replace this [file](https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css-js/.github/workflows/linters.yml) content with your linter.yml file because your linters are only running tests (Webhint, Stylint, LightHouse) but this is not enough it should have a another which is called ESLint. 😨 So Kindly replace this [file](https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css-js/.github/workflows/linters.yml) contents with you linters.yml file contents to run ESLint test 😊

2022-11-24 07:18 UTC, Patfarmurs commented on .eslintrc.json
> +{
Hi, @HAMMAS-SALEEM I did not Understand the requirement.

2022-11-24 09:57 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @Patfarmurs,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly 👍 
✅ Linter checks passed 👍 
✅ Mobile menu features work fine as expected 👍 

## Required Changes ♻️
_Check the comments under the review._

- [x] Kindly work on the broken X icon for closing the mobile menu when clicked. Check the path for loading the image. 
- [ ] Also, the close icon is supposed to be placed at the right end of the screen just as I marked in red on the screenshot. Kindly work on aligning that in order for your design to match the original template 

**You design**
![image](https://user-images.githubusercontent.com/50941074/203753608-afc9fbaa-d2bc-4250-881c-92df37d3580e.png)

**The Original Template**
![image](https://user-images.githubusercontent.com/50941074/203753817-6176c2e0-34da-4293-8415-39230f4c533d.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-11-25 08:47 UTC, DeliceLydia approved these changes
## Hi @Patfarmurs, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



#### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 09:00 UTC, merged